services:
  smaiax-frontend:
    image: smaiax-frontend
    container_name: "smaiax-frontend"
    restart: always
    ports:
      - "8080:8080"
    build:
      context: ./smaiax-frontend
      dockerfile: Dockerfile
    networks:
      - smaiax-network
    depends_on:
      - smaiax-backend

  smaiax-backend:
    image: smaiax-backend
    container_name: "smaiax-backend"
    restart: always
    ports:
      - "5263:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: DockerDevelopment
    build:
      context: ./smaiax-backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - vault
      - rabbitmq
    networks:
      - smaiax-network
  
  vault:
    image: vault:1.13.3
    container_name: "smaiax-vault"
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8200'
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
      VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/:/vault/:rwx
    command:
      - /bin/sh
      - -c
      - |
        dos2unix /vault/config/entrypoint.sh && \
        chmod +x /vault/config/entrypoint.sh && \
        /vault/config/entrypoint.sh
    networks:
      - smaiax-network
    depends_on:
      - postgres

  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: "smaiax-backend-db"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smaiax-db
    networks:
      - smaiax-network
  
  rabbitmq:
    image: rabbitmq:4.0.2-management-alpine
    container_name: smaiax-mqtt-broker
    ports:
      - "15672:15672"  # RabbitMQ Management UI port
      - "1883:1883"  # MQTT port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_management rabbitmq_mqtt && rabbitmq-server"
    networks:
      - smaiax-network

  smaiax-connector:
    image: smaiax-connector
    container_name: smaiax-connector
    build:
      context: ./smaiax-connector
      dockerfile: Dockerfile
    environment:
      DOTNET_ENVIRONMENT: DockerDevelopment
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - smaiax-network

  smaiax-data-generator-1:
    container_name: smaiax-data-generator-1
    build:
      context: ./smaiax-data-generator
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SMART_METER_ID=070dec95-56bb-4154-a2c4-c26faf9fff4d
      - TENANT_ID=4846f8c1-d322-48a3-9d5a-b86219c9e14a
      - MQTT_BROKER_HOST=smaiax-mqtt-broker
      - MQTT_PORT=1883
      - MQTT_USERNAME=user
      - MQTT_PASSWORD=password
      - TIME_INTERVAL=5
    networks:
      - smaiax-network

  smaiax-data-generator-2:
    container_name: smaiax-data-generator-2
    build:
      context: ./smaiax-data-generator
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SMART_METER_ID=74b243fd-188e-48a0-b5d1-4916f5464b0a
      - TENANT_ID=4846f8c1-d322-48a3-9d5a-b86219c9e14a
      - MQTT_BROKER_HOST=smaiax-mqtt-broker
      - MQTT_PORT=1883
      - MQTT_USERNAME=user
      - MQTT_PASSWORD=password
      - TIME_INTERVAL=5
    networks:
      - smaiax-network

  smaiax-data-generator-3:
    container_name: smaiax-data-generator-3
    build:
      context: ./smaiax-data-generator
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SMART_METER_ID=95cc68ed-c94e-40de-851b-b95aaacfb76c
      - TENANT_ID=24f037f5-bcd1-4eaa-9054-d87ca14a7765
      - MQTT_BROKER_HOST=smaiax-mqtt-broker
      - MQTT_PORT=1883
      - MQTT_USERNAME=user
      - MQTT_PASSWORD=password
      - TIME_INTERVAL=5
    networks:
      - smaiax-network

  smaiax-data-generator-4:
    container_name: smaiax-data-generator-4
    build:
      context: ./smaiax-data-generator
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SMART_METER_ID=1da14768-a0ce-432e-93b8-1b31e732c4af
      - TENANT_ID=24f037f5-bcd1-4eaa-9054-d87ca14a7765
      - MQTT_BROKER_HOST=smaiax-mqtt-broker
      - MQTT_PORT=1883
      - MQTT_USERNAME=user
      - MQTT_PASSWORD=password
      - TIME_INTERVAL=5
    networks:
      - smaiax-network

  smaiax-data-generator-5:
    container_name: smaiax-data-generator-5
    build:
      context: ./smaiax-data-generator
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SMART_METER_ID=96ae137c-a687-4423-b7ff-4cb0b238bfc7
      - TENANT_ID=8f864f2c-5a92-4a1a-bf59-a65f2579250d
      - MQTT_BROKER_HOST=smaiax-mqtt-broker
      - MQTT_PORT=1883
      - MQTT_USERNAME=user
      - MQTT_PASSWORD=password
      - TIME_INTERVAL=5
    networks:
      - smaiax-network

  smaiax-data-generator-6:
    container_name: smaiax-data-generator-6
    build:
      context: ./smaiax-data-generator
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SMART_METER_ID=90b05cce-119f-40c4-9b28-e1d3088a109c
      - TENANT_ID=8f864f2c-5a92-4a1a-bf59-a65f2579250d
      - MQTT_BROKER_HOST=smaiax-mqtt-broker
      - MQTT_PORT=1883
      - MQTT_USERNAME=user
      - MQTT_PASSWORD=password
      - TIME_INTERVAL=5
    networks:
      - smaiax-network

networks:
  smaiax-network:
    name: "smaiax-network"
    driver: bridge