services:
  smaiax-frontend:
    image: smaiax-frontend
    container_name: "smaiax-frontend"
    restart: always
    ports:
      - "8080:8080"
    build:
      context: ./smaiax-frontend
      dockerfile: Dockerfile
    networks:
      - smaiax-network
    depends_on:
      - smaiax-backend

  smaiax-backend:
    image: smaiax-backend
    container_name: "smaiax-backend"
    restart: always
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: DockerDevelopment
    build:
      context: ./smaiax-backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - vault
      - rabbitmq
    networks:
      - smaiax-network
  
  vault:
    image: vault:1.13.3
    container_name: "smaiax-vault"
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8200'
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
      VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/:/vault/:rwx
    command:
      - /bin/sh
      - -c
      - |
        dos2unix /vault/config/entrypoint.sh && \
        /vault/config/entrypoint.sh
    networks:
      - smaiax-network
    depends_on:
      - postgres

  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: "smaiax-backend-db"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smaiax-db
    networks:
      - smaiax-network
  
  rabbitmq:
    image: rabbitmq:4.0.2-management-alpine
    container_name: smaiax-mqtt-broker
    ports:
      - "15672:15672"  # RabbitMQ Management UI port
      - "1883:1883"  # MQTT port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_management rabbitmq_mqtt && rabbitmq-server"
    networks:
      - smaiax-network

  smaiax-connector:
    image: smaiax-connector
    container_name: smaiax-connector
    build:
      context: ./smaiax-connector
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - smaiax-network

  smaiax-data-generator:
    container_name: smaiax-data-generator
    build:
      context: ./smaiax-data-generator
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SMART_METER_ID=2f7542f4-9395-40a6-a459-c0fd452b9daa
      - MQTT_BROKER_HOST=smaiax-mqtt-broker
      - MQTT_PORT=1883
      - MQTT_USERNAME=user
      - MQTT_PASSWORD=password
      - TIME_INTERVAL=5
      - TEST_TOPIC=test
    networks:
      - smaiax-network

networks:
  smaiax-network:
    name: "smaiax-network"
    driver: bridge